-- ---------------------------------------------------------------------
-- Job Order lifecycle, 1 of 3 — schema baseline, realtime, access rules
--
-- Everything here is structural: tables that were missing from version
-- control, the realtime publication, and the row-level rules governing who
-- can see and change a dispatch ticket. The lifecycle logic itself is in
-- files 2 to 4.
--
-- Safe to re-run. Every statement is create-or-replace, if-not-exists, or
-- guarded by a catalog check.
-- ---------------------------------------------------------------------


-- =====================================================================
-- 1. Tables that existed only in the Supabase dashboard
--
-- An audit of every table the client queries, against everything created
-- in migrations and in supabase/verify/replica_baseline.sql, found three
-- with no definition anywhere. They were created by hand, so their columns
-- and — more importantly — their RLS policies lived only in the live
-- database, where a change left no trace and got no review.
--
-- These definitions are written to be safe against production: if the
-- tables are already there, nothing changes. They are NOT an attempt to
-- reshape what exists.
-- =====================================================================

-- Per-job-order conversation. Load-bearing under the new lifecycle rather
-- than a convenience: technicians get no automated reminders (they cannot
-- close a job order themselves), so admin chasing an unresolved job does
-- it here.
create table if not exists public.dispatch_ticket_messages (
  id          bigint generated by default as identity primary key,
  ticket_id   text        not null,
  sender_id   uuid        not null,
  sender_name text,
  sender_role text,
  body        text        not null,
  created_at  timestamptz not null default now()
);

create index if not exists dispatch_ticket_messages_ticket_idx
  on public.dispatch_ticket_messages (ticket_id, created_at);

alter table public.dispatch_ticket_messages enable row level security;

-- Read follows the ticket. Deliberately NOT extended to removedWorkerIds:
-- a replaced technician keeps a read-only copy of the job order itself,
-- but the thread belongs to whoever is working it now.
drop policy if exists dtmsg_select on public.dispatch_ticket_messages;
create policy dtmsg_select on public.dispatch_ticket_messages
  for select to authenticated
  using (
    public.is_admin()
    or exists (
      select 1 from public.dispatch_tickets t
      where t.id = dispatch_ticket_messages.ticket_id
        and (t.data -> 'assignedWorkerIds') @> to_jsonb(auth.uid()::text)
    )
  );

-- Posting requires the same access AND that the row carries your own id,
-- so a message cannot be attributed to someone else.
drop policy if exists dtmsg_insert on public.dispatch_ticket_messages;
create policy dtmsg_insert on public.dispatch_ticket_messages
  for insert to authenticated
  with check (
    sender_id = auth.uid()
    and (
      public.is_admin()
      or exists (
        select 1 from public.dispatch_tickets t
        where t.id = dispatch_ticket_messages.ticket_id
          and (t.data -> 'assignedWorkerIds') @> to_jsonb(auth.uid()::text)
      )
    )
  );

-- No update policy at all: a sent message is a record of what was said.
drop policy if exists dtmsg_delete_admin on public.dispatch_ticket_messages;
create policy dtmsg_delete_admin on public.dispatch_ticket_messages
  for delete to authenticated using (public.is_admin());


-- Admin noticeboard, read by everyone.
create table if not exists public.announcements (
  id              bigint generated by default as identity primary key,
  title           text not null,
  body            text,
  pinned          boolean not null default false,
  created_by      uuid,
  created_by_name text,
  created_at      timestamptz not null default now()
);

create index if not exists announcements_pinned_idx
  on public.announcements (pinned desc, created_at desc);

alter table public.announcements enable row level security;

drop policy if exists announcements_select on public.announcements;
create policy announcements_select on public.announcements
  for select to authenticated using (true);

drop policy if exists announcements_write_admin on public.announcements;
create policy announcements_write_admin on public.announcements
  for all to authenticated
  using (public.is_admin()) with check (public.is_admin());


-- One row per technician, latest position. Distinct from
-- technician_location_history (already versioned), which keeps the trail.
create table if not exists public.technician_locations (
  technician_id uuid primary key,
  lat           double precision,
  lng           double precision,
  accuracy      double precision,
  heading       double precision,
  speed         double precision,
  updated_at    timestamptz not null default now()
);

alter table public.technician_locations enable row level security;

-- Admin sees the team; a technician sees only their own row. Location is
-- sensitive enough that one technician should not be able to watch
-- another's movements.
drop policy if exists techloc_select on public.technician_locations;
create policy techloc_select on public.technician_locations
  for select to authenticated
  using (public.is_admin() or technician_id = auth.uid());

drop policy if exists techloc_upsert_self on public.technician_locations;
create policy techloc_upsert_self on public.technician_locations
  for insert to authenticated with check (technician_id = auth.uid());

drop policy if exists techloc_update_self on public.technician_locations;
create policy techloc_update_self on public.technician_locations
  for update to authenticated
  using (technician_id = auth.uid()) with check (technician_id = auth.uid());

drop policy if exists techloc_delete_admin on public.technician_locations;
create policy techloc_delete_admin on public.technician_locations
  for delete to authenticated using (public.is_admin());


-- =====================================================================
-- 2. Realtime publication
--
-- Three client subscriptions were connecting to tables Postgres never
-- published, which fails SILENTLY — the channel opens without error and
-- simply never fires:
--
--   dispatch_ticket_messages  the job order chat, broken since it was
--                             written; messages only ever appeared to the
--                             sender, who refreshes their own list
--   technician_locations      the live tracker map
--   dispatch_tickets          no subscription existed at all, so no ticket
--                             change ever reached another account's screen
--
-- Publishing them is what makes the job order list, the chat and the map
-- update without a manual reload.
-- =====================================================================
do $$
begin
  if not exists (select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='dispatch_tickets') then
    alter publication supabase_realtime add table public.dispatch_tickets;
  end if;

  if not exists (select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='dispatch_ticket_messages') then
    alter publication supabase_realtime add table public.dispatch_ticket_messages;
  end if;

  if not exists (select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='technician_locations') then
    alter publication supabase_realtime add table public.technician_locations;
  end if;
end $$;

-- REPLICA IDENTITY FULL puts the pre-update row in the WAL alongside the
-- new one. Without it an UPDATE's payload carries only the primary key for
-- the "old" record, and the client cannot tell WHICH fields moved — it
-- uses the old row to detect that a technician was just unassigned from a
-- ticket it still has cached. RLS alone won't tell it that, because the
-- ticket simply stops arriving in future.
--
-- Cost is a wider WAL record per update. dispatch_tickets sees a handful
-- of writes per ticket per day, so this is negligible here; it would not
-- be an acceptable default on a high-write table.
alter table public.dispatch_tickets replica identity full;


-- =====================================================================
-- 3. Who can see and change a dispatch ticket
-- =====================================================================

-- Reassignment needs a replaced technician to keep READ access. The old
-- policy matched only on assignedWorkerIds, so removing someone revoked
-- their access instantly and the job order vanished from their app — no
-- record, no reason. Someone who had driven out that morning would have
-- watched the job evaporate.
--
-- removedWorkerIds is an id-only mirror of the richer removedWorkers audit
-- entries. Matching on it restores read access ONLY: dispatch_update_assigned
-- is untouched below, so a replaced technician can read their closed
-- record and cannot acknowledge, report or reopen anything.
drop policy if exists dispatch_select_assigned on public.dispatch_tickets;
create policy dispatch_select_assigned on public.dispatch_tickets
  for select to authenticated
  using (
    public.is_admin()
    or (data -> 'assignedWorkerIds') @> to_jsonb(auth.uid()::text)
    or (data -> 'removedWorkerIds')  @> to_jsonb(auth.uid()::text)
  );

comment on policy dispatch_select_assigned on public.dispatch_tickets is
  'Admins see every ticket. A technician sees a ticket while assigned to it, and continues to see it read-only after being replaced (removedWorkerIds) so the job order closes out on their side with a reason instead of vanishing. Writing still requires current assignment — see dispatch_update_assigned.';


-- The field guard. Admins pass through untouched; for everyone else this
-- normalises admin-only fields back to their previous values and limits
-- which statuses a technician may set.
--
-- Two things changed here for the new lifecycle:
--
--   * 'preparing' and 'in_progress' are now accepted. in_progress is the
--     Arrived at Site tap — without it the trigger silently reverted the
--     write, so arrival appeared to succeed and nothing happened.
--   * 'closed' is deliberately absent. Closing is admin-only, and this is
--     what enforces it at the database rather than trusting the client to
--     hide a button.
--
-- 'open' stays accepted so tickets created before the lifecycle change can
-- still be acknowledged.
create or replace function public.guard_dispatch_worker_fields()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  if public.is_admin() then
    return new;
  end if;

  new.id := old.id;
  new.created_at := old.created_at;

  new.data := new.data
    || jsonb_strip_nulls(jsonb_build_object('assignedWorkerIds',        old.data -> 'assignedWorkerIds'))
    || jsonb_strip_nulls(jsonb_build_object('assignedWorkerNames',      old.data -> 'assignedWorkerNames'))
    || jsonb_strip_nulls(jsonb_build_object('reportAllowedWorkerIds',   old.data -> 'reportAllowedWorkerIds'))
    || jsonb_strip_nulls(jsonb_build_object('reportAllowedWorkerNames', old.data -> 'reportAllowedWorkerNames'))
    || jsonb_strip_nulls(jsonb_build_object('removedWorkers',           old.data -> 'removedWorkers'))
    -- Read access for replaced technicians keys off this array (see the
    -- select policy above), so a non-admin writing it could grant
    -- themselves sight of any ticket in the system.
    || jsonb_strip_nulls(jsonb_build_object('removedWorkerIds',         old.data -> 'removedWorkerIds'))
    || jsonb_strip_nulls(jsonb_build_object('customer',                 old.data -> 'customer'))
    || jsonb_strip_nulls(jsonb_build_object('customerId',               old.data -> 'customerId'))
    || jsonb_strip_nulls(jsonb_build_object('address',                  old.data -> 'address'))
    || jsonb_strip_nulls(jsonb_build_object('scheduledAt',              old.data -> 'scheduledAt'))
    || jsonb_strip_nulls(jsonb_build_object('createdBy',                old.data -> 'createdBy'))
    -- Preserving the closure record means even a hand-crafted request from
    -- an assigned technician cannot forge a closure.
    || jsonb_strip_nulls(jsonb_build_object('closedBy',                 old.data -> 'closedBy'))
    || jsonb_strip_nulls(jsonb_build_object('closedById',               old.data -> 'closedById'))
    || jsonb_strip_nulls(jsonb_build_object('closedAt',                 old.data -> 'closedAt'));

  if new.status is distinct from old.status
     and new.status not in ('open', 'preparing', 'acknowledged', 'in_progress', 'completed') then
    new.status := old.status;
  end if;

  return new;
end;
$$;

comment on function public.guard_dispatch_worker_fields is
  'BEFORE UPDATE guard on dispatch_tickets. Admins pass through untouched. For everyone else it normalises admin-only fields (assignment, report permission, customer, schedule, closure record) back to their previous values and restricts status transitions to open/preparing/acknowledged/in_progress/completed — closing is admin-only and enforced here, not in the client.';
